index:
    path: /
    controller: App\Controller\FrontendController::home

login:
    path: /login
    controller: App\Controller\SecurityController::login

login_clients:
    path: /login-clients
    controller: App\Controller\SecurityController::loginClients

logout:
    path: /logout    

home:
    path: /home
    controller: App\Controller\FrontendController::home

index_info:
    path: /info/
    controller: App\Controller\HomeController::info

translation:
    path: /translation/{lang}/{page}
    controller: App\Controller\FrontendController::userTranslation

set_booking:
    path: /booking
    controller: App\Controller\HomeController::setBooking
    #condition: 'request.isXmlHttpRequest()'
    #methods: [POST]

###
# GET PRODUCT BLOCKED DATES
###
index_available:
    path: /index-available/
    controller: App\Controller\BookingController::getAvailable
    #condition: 'request.isXmlHttpRequest()'

index_admin:
    path: /admin/
    controller: App\Controller\AdminController::html


####
# template ajax load with twig
####

admin_dashboard:
    path: /admin-dashboard/
    controller: App\Controller\AdminController::adminDashboard

##
# COMPANY
##

admin_company_new:
    path: /admin-company-new/
    controller: App\Controller\CompanyController::companyNew

admin_company_add:
    path: /admin-company-add/
    controller: App\Controller\CompanyController::companyAdd
    #condition: 'request.isXmlHttpRequest()'

admin_company_list:
    path: /admin-company-list/
    controller: App\Controller\CompanyController::CompanyList

admin_company_show_edit:
    path: /admin-company-show-edit/
    controller: App\Controller\CompanyController::companyShowEdit
    condition: 'request.isXmlHttpRequest()'

admin_company_edit:
    path: /admin-company-edit/
    controller: App\Controller\CompanyController::companyEdit
    condition: 'request.isXmlHttpRequest()'

##
# PhotoService
##
admin_photo_service_new:
    path: /admin-photo-service-new/
    controller: App\Controller\PhotoServiceController::photoServiceNew

admin_photo_service_add:
    path: /admin-photo-service-add/
    controller: App\Controller\PhotoServiceController::photoServiceAdd

admin_photo_service_list:
    path: /admin-photo-service-list/
    controller: App\Controller\PhotoServiceController::photoServiceList

admin_photo_service_search:
    path: /admin-photo-service-search/
    controller: App\Controller\PhotoServiceController::photoServiceSearch

admin_photo_service_sendEmail:
    path: /admin-photo-sendEmail/
    controller: App\Controller\PhotoServiceController::photoServiceSendEmail
    #condition: 'request.isXmlHttpRequest()'

    #condition: 'request.isXmlHttpRequest()'

##
# PRODUCTS

##

admin_product_new:
    path: /admin-product-new/
    controller: App\Controller\ProductController::productNew

admin_product_add:
    path: /admin-product-add/
    controller: App\Controller\ProductController::productAdd
    #condition: 'request.isXmlHttpRequest()'

admin_product_list:
    path: /admin-product-list/
    controller: App\Controller\ProductController::productList

admin_product_show_edit:
    path: /admin-product-show-edit/
    controller: App\Controller\ProductController::productShowEdit
    condition: 'request.isXmlHttpRequest()'

admin_product_edit:
    path: /admin-product-edit/
    controller: App\Controller\ProductController::productEdit
    condition: 'request.isXmlHttpRequest()'

admin_product_delete:
    path: /admin-product-delete/
    controller: App\Controller\ProductController::productDelete
    #condition: 'request.isXmlHttpRequest()'

admin_product_order:
    path: /admin-product-order/
    controller: App\Controller\ProductController::productOrder
    #condition: 'request.isXmlHttpRequest()'

##
# BOOKINGS ADMIN EVENTS
##

admin_booking:
    path: /admin-booking/
    controller: App\Controller\AdminController::adminBooking

admin_booking_search:
    path: /admin-booking-search
    controller: App\Controller\AdminController::adminBookingSearch
    condition: 'request.isXmlHttpRequest()'

admin_booking_set_status:
    path: /admin-booking-set-status/
    controller: App\Controller\AdminController::adminBookingSetStatus
    #condition: 'request.isXmlHttpRequest()'

admin_booking_send_status:
    path: /admin-booking-send-status/
    controller: App\Controller\AdminController::adminBookingSendStatus
    #condition: 'request.isXmlHttpRequest()'

admin_booking_validate_user:
    path: /admin/booking/validate-user/
    controller: App\Controller\AdminController::bookingValidateUser
    condition: 'request.isXmlHttpRequest()'
    methods: [POST]

##
# AVAILABLE
##

admin_available:
    path: /admin-available/
    controller: App\Controller\AvailableController::adminAvailable

admin_available_new:
    path: /admin-available-new/
    controller: App\Controller\AvailableController::adminAvailableNew

admin_available_create:
    path: /admin-available-create/
    controller: App\Controller\AvailableController::adminAvailableCreate

admin_available_list:
    path: /admin-available-list/
    controller: App\Controller\AvailableController::adminAvailableList

admin_available_edit:
    path: /admin-available-edit/
    controller: App\Controller\AvailableController::adminAvailableEdit

admin_available_delete:
    path: /admin-available-delete/
    controller: App\Controller\AvailableController::adminAvailableDelete

##
# EASY TEXT
##

admin_easy_text:
    path: /admin-easy-text/
    controller: App\Controller\EasyTextController::EasyText
    #condition: 'request.isXmlHttpRequest()'

admin_easy_text_delete:
    path: /admin-easy-text-delete/
    controller: App\Controller\EasyTextController::EasyTextDelete

##
# RGPD
##

admin_rgpd:
    path: /admin-rgpd/
    controller: App\Controller\RgpdController::rgpd
    #condition: 'request.isXmlHttpRequest()'

admin_rgpd_delete:
    path: /admin-easy-rgpd-delete/
    controller: App\Controller\RgpdController::rgpdDelete

admin_rgpd_edit:
    path: /admin-easy-rgpd-edit/
    controller: App\Controller\RgpdController::rgpdEdit

index_rgpd:
    path: /index-rgpd/
    controller: App\Controller\RgpdController::rgpdShow
    #condition: 'request.isXmlHttpRequest()'


##
# ABOUT-US
##

admin_about_us:
    path: /admin-about-us/
    controller: App\Controller\AboutUsController::aboutUs
    #condition: 'request.isXmlHttpRequest()'

admin_about_us_delete:
    path: /admin-about-us-delete/
    controller: App\Controller\AboutUsController::aboutUsDelete

admin_about_us_edit:
    path: /admin-about-us-edit/
    controller: App\Controller\AboutUsController::aboutUsEdit

index_about_us:
    path: /index-about-us/
    controller: App\Controller\AboutUsController::aboutUsShow
    #condition: 'request.isXmlHttpRequest()'

##
# TERMS CONDITIONS
##

admin_terms:
    path: /admin-terms/
    controller: App\Controller\TermsConditionsController::terms
    #condition: 'request.isXmlHttpRequest()'

admin_terms_delete:
    path: /admin-easy-terms-delete/
    controller: App\Controller\TermsConditionsController::termsDelete

admin_terms_edit:
    path: /admin-easy-terms-edit/
    controller: App\Controller\TermsConditionsController::termsEdit

index_terms:
    path: /index-terms/
    controller: App\Controller\TermsConditionsController::termsShow
    #condition: 'request.isXmlHttpRequest()'

##
# WARNING
##

admin_warning:
    path: /admin-warning/
    controller: App\Controller\WarningController::adminWarning

admin_warning_edit:
    path: /admin-warning-edit/
    controller: App\Controller\WarningController::adminWarningEdit

##
# GALLERY
##

admin_gallery:
    path: /admin-gallery/
    controller: App\Controller\GalleryController::gallery

admin_gallery_list:
    path: /admin-gallery-list/
    controller: App\Controller\GalleryController::galleryList

admin_gallery_new:
    path: /admin-gallery-new/
    controller: App\Controller\GalleryController::galleryNew

admin_gallery_delete:
    path: /admin-gallery-delete/
    controller: App\Controller\GalleryController::galleryDelete

admin_gallery_add:
    path: /admin-gallery-add/
    controller: App\Controller\GalleryController::galleryAdd
    #condition: 'request.isXmlHttpRequest()'

admin_gallery_show_edit:
    path: /admin-gallery-show-edit/
    controller: App\Controller\GalleryController::galleryShowEdit
    #condition: 'request.isXmlHttpRequest()'

admin_gallery_edit:
    path: /admin-gallery-edit/
    controller: App\Controller\GalleryController::galleryEdit
    #condition: 'request.isXmlHttpRequest()'

admin_gallery_order:
    path: /admin-gallery-order/
    controller: App\Controller\GalleryController::galleryOrder

##
# BANNER
##

admin_banner:
    path: /admin-banner/
    controller: App\Controller\BannerController::banner

admin_banner_list:
    path: /admin-banner-list/
    controller: App\Controller\BannerController::bannerList

admin_banner_new:
    path: /admin-banner-new/
    controller: App\Controller\BannerController::bannerNew

admin_banner_delete:
    path: /admin-banner-delete/
    controller: App\Controller\BannerController::bannerDelete

admin_banner_add:
    path: /admin-banner-add/
    controller: App\Controller\BannerController::bannerAdd
    #condition: 'request.isXmlHttpRequest()'

admin_banner_show_edit:
    path: /admin-banner-show-edit/
    controller: App\Controller\BannerController::bannerShowEdit
    #condition: 'request.isXmlHttpRequest()'

admin_banner_edit:
    path: /admin-banner-edit/
    controller: App\Controller\BannerController::bannerEdit
    #condition: 'request.isXmlHttpRequest()'

admin_banner_order:
    path: /admin-banner-order/
    controller: App\Controller\BannerController::bannerOrder


##
# MENU
##

admin_menu:
    path: /admin-menu/
    controller: App\Controller\MenuController::menu

admin_menu_list:
    path: /admin-menu-list/
    controller: App\Controller\MenuController::menuList

admin_menu_new:
    path: /admin-menu-new/
    controller: App\Controller\MenuController::menuNew

admin_menu_delete:
    path: /admin-menu-delete/
    controller: App\Controller\MenuController::menuDelete

admin_menu_add:
    path: /admin-menu-add/
    controller: App\Controller\MenuController::menuAdd
    #condition: 'request.isXmlHttpRequest()'

admin_menu_show_edit:
    path: /admin-menu-show-edit/
    controller: App\Controller\MenuController::menuShowEdit
    #condition: 'request.isXmlHttpRequest()'

admin_menu_edit:
    path: /admin-menu-edit/
    controller: App\Controller\MenuController::menuEdit
    #condition: 'request.isXmlHttpRequest()'

admin_menu_order:
    path: /admin-menu-order/
    controller: App\Controller\MenuController::menuOrder


##
# CATEGORY
##

admin_category:
    path: /admin-category/
    controller: App\Controller\CategoryController::category

admin_category_list:
    path: /admin-category-list/
    controller: App\Controller\CategoryController::categoryList

admin_category_new:
    path: /admin-category-new/
    controller: App\Controller\CategoryController::categoryNew

admin_category_delete:
    path: /admin-category-delete/
    controller: App\Controller\CategoryController::categoryDelete

admin_category_add:
    path: /admin-category-add/
    controller: App\Controller\CategoryController::categoryAdd
    #condition: 'request.isXmlHttpRequest()'

admin_category_show_edit:
    path: /admin-category-show-edit/
    controller: App\Controller\CategoryController::categoryShowEdit
    #condition: 'request.isXmlHttpRequest()'

admin_category_edit:
    path: /admin-category-edit/
    controller: App\Controller\CategoryController::categoryEdit
    #condition: 'request.isXmlHttpRequest()'

##
# USERS
##

user_list:
    path: /user-list/
    controller: App\Controller\UserController::listUser

status_user:
    path: /status-user/
    controller: App\Controller\UserController::statusUser
    #condition: 'request.isXmlHttpRequest()'

delete_user:
    path: /delete-user/
    controller: App\Controller\UserController::deleteUser
    #condition: 'request.isXmlHttpRequest()'

password_user:
    path: /password-user/
    controller: App\Controller\UserController::passwordUser
    #condition: 'request.isXmlHttpRequest()'

user_new:
    path: /user-new/{userType}
    controller: App\Controller\RegistrationController::userNew

user_create:
    path: /user-create/
    controller: App\Controller\RegistrationController::userCreate

    ###
# PAGES
###

other_company:
    path: /other_company
    controller: App\Controller\FrontendController::otherCompany

photo_service:
    path: /photo_service
    controller: App\Controller\FrontendController::photoService

photo_service_download:
    path: /photo_service_download
    controller: App\Controller\FrontendController::photoServiceDownload

photo_service_preview:
    path: /photo_service_preview
    controller: App\Controller\FrontendController::photoServicePreview

about_us:
    path: /about-us
    controller: App\Controller\FrontendController::aboutUs

activity:
    path: /activity/{id}/{text}
    controller: App\Controller\FrontendController::activity


page_detail:
    path: /page/{page}/{pageSub}
    controller: App\Controller\FrontendController::pageDetail
    
product_detail:
    path: /product/{page}/{pageSub}
    controller: App\Controller\FrontendController::productDetail
    
private_detail:
    path: /private/{page}/{pageSub}
    controller: App\Controller\FrontendController::privateDetail
    
send_email:
    path: /send-email/
    controller: App\Controller\FrontendController::sendEmail

   
# send_voucher:
#     path: /send-voucher/
#     controller: App\Controller\FrontendController::sendVoucher
   
